### ISSUE TITLE
Update on potential release

### ISSUE THREAD

**Issue by SRJames** [ParticularLabs/NServiceBus.AwsLambda#7]
Hi, could you provide an update on whether you think this library is likely to make it into production?

**Comment by kbaley** [comment]
Hi @SRJames. At this point, all I can accurately say is that the library is in the early stages and we can't provide an estimate on when, or if, it will go into production. If it does, the repo will be moved to our main organization at https://github.com/Particular. It's definitely an area we're interested in pursuing and I'll make a note of your interest in it.

Your best bet is to watch the repository and our [Twitter account](https://twitter.com/ParticularSW) for updates.

**Comment by WilliamBZA** [comment]
@SRJames Can you drop me a mail please? We'd like to discuss this package with you further. You can send a mail to our support (support at particular) address, making the subject line "For william".
